### ISSUE TITLE
when intgrating in CKeditor can't find select

### ISSUE THREAD

**Issue by johnef** [Krato/Laravel-5-File-Manager#2]
when integrating in CKeditor can't find select in the menu or anywhere else 
how to use the image that I need in the editor

**Comment by johnef** [comment]
@Krato any action please

**Comment by Krato** [comment]
I will update the readme this week. Sorry I'm a little bit busy.

**Comment by Krato** [comment]
Update to 2.2 version.

There is also an easy guide now on readme: [How to use dialog](https://github.com/Krato/Laravel-5-File-Manager/blob/master/dialog.md)
