### ISSUE TITLE
Can't upload video more than 80 MB?

### ISSUE THREAD

**Issue by perpetual-claudius** [Krato/Laravel-5-File-Manager#6]
I tried to upload video more then 300 MB but it failed. Kindly provide the solution for this

**Comment by Krato** [comment]
Hello @mail2perpetua. This should be a problem of your php configuration. Please check: https://stackoverflow.com/questions/2184513/change-the-maximum-upload-file-size

**Comment by perpetual-claudius** [comment]
@Krato Already i find and solve this issue ThankYou
